import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google"; 
import "./style.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin",], weight:["400"] });


export const metadata: Metadata = {
  title: "Sayangku Santi Mantondang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
